name: jdenticon
description: A starting point for Dart libraries or applications.
version: 1.0.0
author: videah <videah@selfish.systems>
repository: https://github.com/videah/jdenticon-dart
homepage: https://github.com/videah/jdenticon-dart

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  crypto: ^2.0.6

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
